### ISSUE TITLE
 saveDataEditor/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0)

### ISSUE THREAD

**Issue by ttpro1995** [ghjbku/dataEditorProject#1]
$ java -jar saveDataEditor-1.0.3-SNAPSHOT.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: saveDataEditor/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by ttpro1995** [comment]
Default installation Java version on window 10 is java 8 (https://www.java.com/en/download/why-java-8-recommended.html) 

So, if you build java with java 11, then user have somehow get java 11 install on their PC. This is a difficult situation for whom not developer.

**Comment by ghjbku** [comment]
thank you for the feedback, i will research what i can do , how simple a version downgrade is.

**Comment by ghjbku** [comment]
i will have to test the solution when i get back home next week, if all is well, i will be using java1.8 instead to further develop the project.

**Comment by ghjbku** [comment]
java downgrade itself isn't the problematic field, its javafx that needs to be manually built/(or use openjdk that includes jfx) as maven only has jfx 11 or higher :/
